### ISSUE TITLE
missing license.

### ISSUE THREAD

**Issue by gerblesh** [AsherGlick/Gizmo#1]
consider adding a license to the project, here's a great resource for licensing: https://choosealicense.com/. I would personally suggest licensing this project under MIT so people could use this in their games.

**Comment by AsherGlick** [comment]
Woah, never thought I would be the one being told to put a license on one of my projects. Even the best can forget I guess.

849a68d6b925b891d1a86dc89fd60f3461479a63 takes care of this. A nice and permissive BSD license.
